blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/Spellhold-Studios/Infinity-Animations/discussions
    about: Ask a question, give a suggestion or share your opinion in discussions.
  - name: Contributing Guidelines
    url: https://github.com/Spellhold-Studios/.github/blob/main/CONTRIBUTING.md
    about: A complete guide to foster a positive experience for contributors and maintainers.
  - name: GitHub Support
    url: https://support.github.com/contact
    about: Please contact GitHub Support if you need help with your GitHub account.
