//Pit fiend routine
SILENT
COPY_EXISTING ~%nb%.cre~ ~override~
  PATCH_IF SOURCE_SIZE > 0x2d3 BEGIN
    PATCH_IF rgp = 1 BEGIN
      WRITE_SHORT 0x28 0x5035 //Animation (pit_fiend_nwn)
      WRITE_BYTE 0x2d 47 //Minor color (pure dark red)
      WRITE_BYTE 0x2e 46 //Major color (red)
      WRITE_BYTE 0x2f 46 //Skin color
      LAUNCH_PATCH_FUNCTION DELETE_CRE_EFFECT
        INT_VAR opcode_to_delete = 51 //Strong-dark by RGB
      END
    END
  END
BUT_ONLY
VERBOSE
