//Seer routine
SILENT
COPY_EXISTING ~%nb%.cre~ ~override~
  PATCH_INCLUDE ~infinityanimations/lib/fj_cre_validity.tpp~
  PATCH_IF vl BEGIN
    PATCH_INCLUDE ~infinityanimations/lib/fj_cre_reindex.tpp~
    PATCH_IF rgs = 1 BEGIN
      WRITE_SHORT 0x28 0x528a //Animation (seer_iwd)
      READ_BYTE 0x237 sx //Sex
      PATCH_IF sx = 0 BEGIN
        WRITE_BYTE 0x237 1 //male
      END
    END
  END
BUT_ONLY
VERBOSE
